### ISSUE TITLE
Notifcation action buttons should match Skiff design system

### ISSUE THREAD

**Issue by jgdevelopment** [skiff-org/skiff-windows-app#23]
<img width="1233" alt="CleanShot 2023-11-01 at 16 23 32@2x" src="https://github.com/skiff-org/skiff-windows-app/assets/3527315/caa4d069-d08a-4d84-aaf9-b93752697944">

In this case about 33px tall. Can see exact component https://github.com/skiff-org/skiff-ui/tree/main/src/components/Button.

**Comment by Novack** [comment]
The notifications in the Skiff Windows App are part of the Windows API, not part of the Skiff Cloud side and as such, its visuals are standard and made by Microsoft to respect the Windows theme.

Edit: Well @jgdevelopment sorry, I thought this was a ticket from some random person in the internet 😅
I guess you mean something else, but do let me know if any of the recent work needs clarification. Cheers!
